---
title: "Untitled"
author: "Henry Siegler"
date: "2023-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(kableExtra)
library(knitr)

opioid_deaths_data <- read.delim(here("OpioidOverdosesCleaned.txt"))

opioid_deaths_data <- opioid_deaths_data[,c(2, 4, 6, 7, 8)]
```

```{r}
opioid_deaths_data$Crude <- ifelse(opioid_deaths_data$Crude.Rate == "Unreliable", NA, opioid_deaths_data$Crude.Rate)

opioid_deaths_data <- opioid_deaths_data %>% 
  mutate(Crude = as.numeric(Crude)) %>% 
  drop_na()


quantile_overall <- quantile(opioid_deaths_data$Crude, probs = c(0.05, 0.25, 0.5, 0.75, 0.95))

quantile_2000 <- opioid_deaths_data %>% 
  filter(Year == 2000) %>% 
  pull(Crude) %>% 
  quantile(probs = c(0.05, 0.25, 0.5, 0.75, 0.95))

quantile_2005 <- opioid_deaths_data %>% 
  filter(Year == 2005) %>% 
  pull(Crude) %>% 
  quantile(probs = c(0.05, 0.25, 0.5, 0.75, 0.95))

quantile_2010 <- opioid_deaths_data %>% 
  filter(Year == 2010) %>% 
  pull(Crude) %>% 
  quantile(probs = c(0.05, 0.25, 0.5, 0.75, 0.95))

quantile_2015 <- opioid_deaths_data %>% 
  filter(Year == 2015) %>% 
  pull(Crude) %>% 
  quantile(probs = c(0.05, 0.25, 0.5, 0.75, 0.95))

quantile_2020 <- opioid_deaths_data %>% 
  filter(Year == 2020) %>% 
  pull(Crude) %>% 
  quantile(probs = c(0.05, 0.25, 0.5, 0.75, 0.95))


quantiles_df <- data.frame(quantile_overall,
                           quantile_2000,
                           quantile_2005,
                           quantile_2010,
                           quantile_2015,
                           quantile_2020)

quantiles_df <- t(quantiles_df)

rownames(quantiles_df) <- c("1999 - 2020",
                            "2000",
                            "2005",
                            "2010",
                            "2015",
                            "2020")

quantiles_df <- round(quantiles_df, 2)

kableExtra::kable(quantiles_df, format = "html", caption = "Quantiles of the Opioid Overdose Rate in Select Years") %>% 
  kable_styling(full_width = TRUE)
```


```{r}
opioid_deaths_data %>% 
  mutate(crude = as.numeric(Crude.Rate)) %>% 
  group_by(Year) %>% 
  summarise(mean = mean(crude, na.rm= TRUE)) %>% 
  ggplot(aes(x = Year, y= mean)) + 
  geom_line() + 
  geom_point() + 
  ylab("Average Opioid Overdose Death Rate per 100K") + 
  theme_minimal()
```


$$Y_{s,\ t} = \alpha_s + \gamma_t + \beta_1 Time + \beta_2 PDMP + \beta_3 TimeSincePDMP + \beta_4 PDMP * Time + \beta_{5-10} X'_{s,\ t} + \epsilon_{s,\ t}$$


$$Y_{s,\ t} = \alpha_s + \gamma_t +  \beta_2 PDMP_{s,\ t} + \beta_2 YearsAfterPDMP_{s,\ t} + \sum_{k =1}^K \theta_k X_{s,\ t}^k + \epsilon_{s,\ t}$$
$$Y_{s,\ t} = \alpha_s + \gamma_t +  \beta_1 PDMP_{s,\ t} + \sum_{k =1}^K \theta_k X_{s,\ t}^k + \epsilon_{s,\ t}$$

$$Y_{s,\ t} = \alpha_s + \gamma_t +  \beta_1 PDMP_{s,\ t} + \epsilon_{s,\ t}$$

```{r}
PDMP_Year <- readxl::read_xlsx(here("PDMPYear.xlsx"))
PDMP_Year <- PDMP_Year %>% 
  mutate(Year = as.numeric(Year)) %>% 
  rename(operational_year = Year)

cumulative_PDMPS <- PDMP_Year %>% 
  group_by(operational_year) %>% 
  summarise(count = n_distinct(State)) %>% 
  mutate(cumulative_count = cumsum(count))

cumulative_PDMPS %>% 
  ggplot(aes(x = operational_year, y = cumulative_count)) + 
  geom_point(size = 3) + 
  geom_line() + 
  theme_minimal() + 
  labs(y = "Total Number of States with an Operational PDMP",
       x = "Year",
       title = "Number of PDMPs over Time")+
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_x_continuous(breaks = seq(1940, 2020, by = 10))
```

















Words

